"""empty message

Revision ID: dd3e26bd0838
Revises: 212f19f02e08
Create Date: 2022-07-03 20:12:34.968999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3e26bd0838'
down_revision = '212f19f02e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
